/**
 * Centralized list and map of live symbols supported by Yahoo Finance, TEFAS and borsats.
 *
 * ⚠️ LİSANS & KULLANIM UYARISI:
 * Bu projede kullanılan `@muhammedaksam/borsats` kütüphanesinin lisansı "kişisel ve eğitim amaçlı kullanım"
 * ile sınırlıdır; ticari ürün/servis geliştirmede doğrudan kullanılamaz. Defter kişisel/tek kullanıcılı bir
 * portföy takip uygulaması olduğu için uygundur. Projenin ticarileştirilmesi durumunda lisanslı/resmi bir veri
 * sağlayıcı API'sine (BIST/Matriks/Ideal vb.) geçiş yapılması gerekmektedir.
 */

export const SYMBOL_MAP: Record<string, string> = {
  // BIST Stocks
  THYAO: "THYAO.IS",
  PGSUS: "PGSUS.IS",
  TAVHL: "TAVHL.IS",
  ASELS: "ASELS.IS",
  SDTTR: "SDTTR.IS",
  MIATK: "MIATK.IS",
  LOGO: "LOGO.IS",
  REEDR: "REEDR.IS",
  FROTO: "FROTO.IS",
  TOASO: "TOASO.IS",
  DOAS: "DOAS.IS",
  OTKAR: "OTKAR.IS",
  ARCLK: "ARCLK.IS",
  VESTL: "VESTL.IS",
  TUPRS: "TUPRS.IS",
  ENJSA: "ENJSA.IS",
  ASTOR: "ASTOR.IS",
  KONTR: "KONTR.IS",
  CWENE: "CWENE.IS",
  EUPWR: "EUPWR.IS",
  ODAS: "ODAS.IS",
  AKBNK: "AKBNK.IS",
  GARAN: "GARAN.IS",
  ISCTR: "ISCTR.IS",
  YKBNK: "YKBNK.IS",
  VAKBN: "VAKBN.IS",
  ISMEN: "ISMEN.IS",
  KCHOL: "KCHOL.IS",
  SAHOL: "SAHOL.IS",
  ALARK: "ALARK.IS",
  ENKAI: "ENKAI.IS",
  SISE: "SISE.IS",
  EREGL: "EREGL.IS",
  KRDMD: "KRDMD.IS",
  BIMAS: "BIMAS.IS",
  MGROS: "MGROS.IS",
  SOKM: "SOKM.IS",
  CCOLA: "CCOLA.IS",
  TCELL: "TCELL.IS",
  // BIST IPO & New Market Stocks
  HOROZ: "HOROZ.IS",
  KOTON: "KOTON.IS",
  KOCMT: "KOCMT.IS",
  MOGAN: "MOGAN.IS",
  RGYAS: "RGYAS.IS",
  ENTRA: "ENTRA.IS",
  LILAK: "LILAK.IS",
  HRKET: "HRKET.IS",
  ALTNY: "ALTNY.IS",
  OBAMS: "OBAMS.IS",
  ICUGS: "ICUGS.IS",
  TEKMN: "TEKMN.IS",
  GUNDG: "GUNDG.IS",
  BAHKM: "BAHKM.IS",
  ARTMS: "ARTMS.IS",
  ONRYT: "ONRYT.IS",
  DURKN: "DURKN.IS",
  DCTTR: "DCTTR.IS",
  EFORC: "EFORC.IS",
  AHSGY: "AHSGY.IS",
  TABGD: "TABGD.IS",
  BEGYO: "BEGYO.IS",
  SURGY: "SURGY.IS",
  BORLS: "BORLS.IS",
  DOFER: "DOFER.IS",
  MARBL: "MARBL.IS",
  TARKM: "TARKM.IS",
  HATSAN: "HATSAN.IS",
  GOKNR: "GOKNR.IS",
  CVKMD: "CVKMD.IS",
  KOPOL: "KOPOL.IS",
  IZENR: "IZENR.IS",
  TATEN: "TATEN.IS",
  ENERY: "ENERY.IS",
  ASGYO: "ASGYO.IS",
  OFSYM: "OFSYM.IS",
  KTSKR: "KTSKR.IS",
  DMRGD: "DMRGD.IS",

  // US Stocks (S&P 500, NASDAQ 100, Dow Jones Major Constituents)
  AAPL: "AAPL",
  MSFT: "MSFT",
  NVDA: "NVDA",
  GOOGL: "GOOGL",
  AMZN: "AMZN",
  META: "META",
  TSLA: "TSLA",
  AVGO: "AVGO",
  ORCL: "ORCL",
  CRM: "CRM",
  ADBE: "ADBE",
  NFLX: "NFLX",
  AMD: "AMD",
  QCOM: "QCOM",
  INTC: "INTC",
  PLTR: "PLTR",
  UBER: "UBER",
  ABNB: "ABNB",
  NOW: "NOW",
  INTU: "INTU",
  PANW: "PANW",
  CRWD: "CRWD",
  SNOW: "SNOW",
  AMAT: "AMAT",
  LRCX: "LRCX",
  MU: "MU",
  JPM: "JPM",
  BAC: "BAC",
  GS: "GS",
  MS: "MS",
  V: "V",
  MA: "MA",
  AXP: "AXP",
  "BRK.B": "BRK-B",
  "BRK-B": "BRK-B",
  BLK: "BLK",
  C: "C",
  WFC: "WFC",
  PNC: "PNC",
  LLY: "LLY",
  UNH: "UNH",
  JNJ: "JNJ",
  ABBV: "ABBV",
  MRK: "MRK",
  PFE: "PFE",
  TMO: "TMO",
  ABT: "ABT",
  DHR: "DHR",
  ISRG: "ISRG",
  XOM: "XOM",
  CVX: "CVX",
  COP: "COP",
  SLB: "SLB",
  NEE: "NEE",
  WMT: "WMT",
  COST: "COST",
  PG: "PG",
  KO: "KO",
  PEP: "PEP",
  MCD: "MCD",
  NKE: "NKE",
  SBUX: "SBUX",
  HD: "HD",
  LOW: "LOW",
  TJX: "TJX",
  CAT: "CAT",
  GE: "GE",
  BA: "BA",
  RTX: "RTX",
  LMT: "LMT",
  HON: "HON",
  UNP: "UNP",
  UPS: "UPS",
  DE: "DE",
  DIS: "DIS",
  CMCSA: "CMCSA",
  T: "T",
  VZ: "VZ",
  TXN: "TXN",
  KLAC: "KLAC",
  CDNS: "CDNS",
  SNPS: "SNPS",
  MRVL: "MRVL",
  ANET: "ANET",
  MCHP: "MCHP",
  ON: "ON",
  ADI: "ADI",
  FTNT: "FTNT",
  WDAY: "WDAY",
  TEAM: "TEAM",
  DDOG: "DDOG",
  MDB: "MDB",
  COIN: "COIN",
  PYPL: "PYPL",
  BK: "BK",
  SPGI: "SPGI",
  MCO: "MCO",
  ICE: "ICE",
  CME: "CME",
  SCHW: "SCHW",
  CVS: "CVS",
  CI: "CI",
  ELV: "ELV",
  BMY: "BMY",
  AMGN: "AMGN",
  GILD: "GILD",
  VRTX: "VRTX",
  REGN: "REGN",
  SYK: "SYK",
  MDT: "MDT",
  BSX: "BSX",
  BDX: "BDX",
  EW: "EW",
  EOG: "EOG",
  OXY: "OXY",
  MPC: "MPC",
  VLO: "VLO",
  PSX: "PSX",
  KMI: "KMI",
  WMB: "WMB",
  DUK: "DUK",
  SO: "SO",
  AEP: "AEP",
  SRE: "SRE",
  TGT: "TGT",
  MDLZ: "MDLZ",
  KMB: "KMB",
  CL: "CL",
  MNST: "MNST",
  BKNG: "BKNG",
  MAR: "MAR",
  HLT: "HLT",
  LVS: "LVS",
  ORLY: "ORLY",
  AZO: "AZO",
  ROST: "ROST",
  GWW: "GWW",
  FAST: "FAST",
  CTAS: "CTAS",
  ITW: "ITW",
  EMR: "EMR",
  ETN: "ETN",
  PH: "PH",
  TT: "TT",
  CARR: "CARR",
  FDX: "FDX",
  CSX: "CSX",
  NSC: "NSC",
  WM: "WM",
  RSG: "RSG",
  ECL: "ECL",

  // European Stocks (DAX, CAC 40, FTSE 100, SMI, AEX, IBEX, FTSE MIB)
  ASML: "ASML.AS",
  INGA: "INGA.AS",
  PHIA: "PHIA.AS",
  HEIA: "HEIA.AS",
  SAP: "SAP.DE",
  SIE: "SIE.DE",
  ALV: "ALV.DE",
  BAS: "BAS.DE",
  VOW3: "VOW3.DE",
  MBG: "MBG.DE",
  BMW: "BMW.DE",
  DTE: "DTE.DE",
  BAYN: "BAYN.DE",
  MUV2: "MUV2.DE",
  MC: "MC.PA",
  OR: "OR.PA",
  "TTE.PA": "TTE.PA",
  SAN: "SAN.PA",
  AIR: "AIR.PA",
  RMS: "RMS.PA",
  SU: "SU.PA",
  BNP: "BNP.PA",
  NESN: "NESN.SW",
  NOVN: "NOVN.SW",
  ROG: "ROG.SW",
  UBSG: "UBSG.SW",
  CFR: "CFR.SW",
  SHEL: "SHEL.L",
  AZN: "AZN.L",
  HSBA: "HSBA.L",
  ULVR: "ULVR.L",
  BP: "BP.L",
  GSK: "GSK.L",
  REL: "REL.L",
  RIO: "RIO.L",
  "NOVO-B": "NOVO-B.CO",
  ITX: "ITX.MC",
  "SAN.MC": "SAN.MC",
  RACE: "RACE.MI",
  ENEL: "ENEL.MI",

  // ETFs & Funds
  QQQ: "QQQ",
  SPY: "SPY",
  VOO: "VOO",
  VTI: "VTI",
  GLD: "GLD",
  SLV: "SLV",
  SMH: "SMH",
  SOXX: "SOXX",
  DIA: "DIA",
  SCHD: "SCHD",
  VYM: "VYM",
  XLF: "XLF",
  XLK: "XLK",
  XLE: "XLE",
  XLV: "XLV",
  XLI: "XLI",
  XLP: "XLP",
  XLY: "XLY",
  XLU: "XLU",
  VNQ: "VNQ",
  TLT: "TLT",
  AGG: "AGG",
  BND: "BND",
  VEA: "VEA",
  VWO: "VWO",
  EFA: "EFA",
  IWM: "IWM",
  ARKK: "ARKK",
  TQQQ: "TQQQ",
  SQQQ: "SQQQ",

  // Currencies & FX
  "USD/TRY": "USDTRY=X",
  "EUR/TRY": "EURTRY=X",
  "GBP/TRY": "GBPTRY=X",
  "CHF/TRY": "CHFTRY=X",
  "EUR/USD": "EURUSD=X",

  // Commodities & Futures
  GOLD_OUNCE: "GC=F",
  SILVER_OUNCE: "SI=F",
  PLATINUM_OUNCE: "PL=F",
  BRENT: "BZ=F",
  BAKIR: "HG=F",

  // Dynamically Derived Precious Metals in TRY (computed in /api/prices from spot ounce & USD/TRY)
  "ALTIN/GR": "ALTIN/GR",
  "GÜMÜŞ/GR": "GÜMÜŞ/GR",
  "GUMUS/GR": "GÜMÜŞ/GR",
  "PLATIN/GR": "PLATIN/GR",
  CEYREK: "CEYREK",
  YARIM: "YARIM",
  TAM: "TAM",
  ATA: "ATA",

  // Market & Sector Indices
  "BIST 100": "XU100.IS",
  "BIST 30": "XU030.IS",
  "BIST Banka": "XBANK.IS",
  "BIST Sınai": "XUSIN.IS",
  "BIST Teknoloji": "XTEK.IS",
  "BIST GYO": "XGMYO.IS",
  "BIST Temettü": "XTMTU.IS",
  "S&P 500": "^GSPC",
  NASDAQ: "^IXIC",
  "ABD 10Y Tahvil": "^TNX",
  "VIX Korku": "^VIX",
  "DXY Dolar": "DX-Y.NYB",

  // TEFAS Yatırım Fonları
  TI2: "TEFAS:TI2",
  TCD: "TEFAS:TCD",
  MAC: "TEFAS:MAC",
  NNF: "TEFAS:NNF",
  IPB: "TEFAS:IPB",
  AFT: "TEFAS:AFT",
  YAY: "TEFAS:YAY",
  BUY: "TEFAS:BUY",
  GMR: "TEFAS:GMR",
  ZCN: "TEFAS:ZCN",
  KTM: "TEFAS:KTM",
  IIH: "TEFAS:IIH",
  KZL: "TEFAS:KZL",
  BIO: "TEFAS:BIO",
  IHK: "TEFAS:IHK",
  TTE: "TEFAS:TTE",
  AFO: "TEFAS:AFO",
  GZH: "TEFAS:GZH",
  ZKP: "TEFAS:ZKP",
  TGE: "TEFAS:TGE",
  KZG: "TEFAS:KZG",
  IDG: "TEFAS:IDG",
  YHK: "TEFAS:YHK",
  TKF: "TEFAS:TKF",
  GBE: "TEFAS:GBE",
  ST1: "TEFAS:ST1",
  HVT: "TEFAS:HVT",
  TI1: "TEFAS:TI1",
};

/**
 * Explicit set of symbols that are either fetched directly from Yahoo Finance
 * or dynamically calculated on-the-fly from live spot quotes (Gram Altın, Çeyrek, etc.).
 */
export const LIVE_SYMBOLS = new Set<string>(Object.keys(SYMBOL_MAP).map((k) => k.toUpperCase()));

export const DYNAMICALLY_DERIVED_SYMBOLS = new Set<string>([
  "ALTIN/GR",
  "GÜMÜŞ/GR",
  "GUMUS/GR",
  "PLATIN/GR",
  "CEYREK",
  "YARIM",
  "TAM",
  "ATA",
  "USD/TRY",
  "EUR/TRY",
  "GBP/TRY",
  "CHF/TRY",
  "EUR/USD",
  "BRENT",
]);

export function isLiveSymbol(symbol: string): boolean {
  if (!symbol) return false;
  const upper = symbol.toUpperCase().trim();
  if (LIVE_SYMBOLS.has(upper) || DYNAMICALLY_DERIVED_SYMBOLS.has(upper)) return true;
  // All BIST stock symbols (3 to 6 alphanumeric characters) and TEFAS fund codes supported via borsats
  if (/^[A-Z0-9]{3,6}$/.test(upper) && !upper.includes("/")) {
    return true;
  }
  // International tickers (e.g. ASML, SAP.DE, MC.PA, SHEL.L, BRK-B)
  if (/^[A-Z0-9.\-]{1,10}$/.test(upper)) {
    return true;
  }
  return false;
}

export function getSymbolTicker(symbol: string): string {
  if (!symbol) return "";
  const upper = symbol.toUpperCase().trim();
  if (SYMBOL_MAP[upper]) return SYMBOL_MAP[upper];
  if (/^[A-Z0-9]{3,6}$/.test(upper) && !upper.includes("/") && !upper.includes(".")) {
    return `${upper}.IS`;
  }
  return upper;
}
